# Generated by Django 3.0.2 on 2020-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='enter student first name', max_length=240)),
                ('lastName', models.CharField(help_text='enter student last name', max_length=240)),
                ('skills', models.CharField(help_text='enter students skills', max_length=240)),
            ],
        ),
    ]
